import type { IconType } from "react-icons";
import {
  SiCloudflare, SiAmazon, SiAwsorganizations, SiKubernetes, SiIstio, SiNginx,
  SiTraefikproxy, SiOpenpolicyagent, SiHelm, SiArgo, SiTerraform, SiGithubactions,
  SiPrometheus, SiGrafana, SiOpentelemetry, SiPostgresql, SiMongodb, SiRedis,
  SiLetsencrypt, SiSonarqube, SiDocker, SiGit, SiGithub,
} from "react-icons/si";
import { FaAws, FaShieldAlt, FaLock, FaDatabase, FaCloud, FaCogs, FaServer, FaNetworkWired, FaKey, FaBell, FaChartLine } from "react-icons/fa";

export type LayerId = "edge" | "ingress" | "security" | "workloads" | "data" | "cloud" | "platform";

export interface OpsNode {
  id: string;
  name: string;
  layer: LayerId;
  Icon: IconType;
  color: string;
  desc: string;
  role: string;
  best: string[];
  cmds: string[];
  docs?: string;
  metrics: { label: string; value: string }[];
}

export interface Layer {
  id: LayerId;
  title: string;
  emoji: string;
  Icon: IconType;
  color: string;
  desc: string;
}

export const LAYERS: Layer[] = [
  { id: "edge",      title: "Edge",           emoji: "🌍", Icon: FaCloud,        color: "#F38020", desc: "Global traffic entry, DNS, CDN, WAF" },
  { id: "ingress",   title: "Ingress",        emoji: "🚪", Icon: FaNetworkWired, color: "#22c55e", desc: "L7 routing, service mesh, gateways" },
  { id: "security",  title: "Security",       emoji: "🔒", Icon: FaLock,         color: "#ef4444", desc: "Policies, secrets, image signing, IRSA" },
  { id: "workloads", title: "Workloads",      emoji: "📦", Icon: SiKubernetes,   color: "#326CE5", desc: "Deployments, pods, jobs — the business" },
  { id: "data",      title: "Data & State",   emoji: "💾", Icon: FaDatabase,     color: "#a855f7", desc: "RDS, caches, volumes, backups" },
  { id: "cloud",     title: "Cloud Services", emoji: "☁️", Icon: FaAws,          color: "#FF9900", desc: "Managed AWS services glue" },
  { id: "platform",  title: "Platform",       emoji: "⚙️", Icon: FaCogs,         color: "#06b6d4", desc: "EKS, GitOps, IaC, observability" },
];

export const NODES: OpsNode[] = [
  // Edge
  { id: "cloudflare", name: "Cloudflare", layer: "edge", Icon: SiCloudflare, color: "#F38020",
    desc: "Global CDN + DDoS + WAF at the edge.",
    role: "Absorbs L3-L7 attacks, caches assets, enforces zero-trust rules.",
    best: ["Enable Bot Fight Mode", "Turn on Under Attack for spikes", "Cache HTML with edge rules"],
    cmds: ["curl -I https://app.example.com", "cloudflared tunnel run web"],
    metrics: [{label:"Latency",value:"12ms"},{label:"Requests",value:"1.2M/s"},{label:"Blocked",value:"842"}]},
  { id: "route53", name: "Route53", layer: "edge", Icon: FaAws, color: "#8C4FFF",
    desc: "Authoritative DNS with health-checked routing.",
    role: "Weighted, latency, and failover records for multi-region.",
    best: ["Use health checks for failover", "Alias records to ALB/CloudFront", "Short TTL for canaries"],
    cmds: ["aws route53 list-hosted-zones", "dig +short app.example.com"],
    metrics: [{label:"Queries",value:"850k/m"},{label:"Zones",value:"14"},{label:"Health",value:"OK"}]},
  { id: "cloudfront", name: "CloudFront", layer: "edge", Icon: FaAws, color: "#8C4FFF",
    desc: "AWS CDN with Lambda@Edge and OAC to S3.",
    role: "Global caching + signed URLs for private assets.",
    best: ["Enable OAC over legacy OAI", "Cache-Control at origin", "Compress objects automatically"],
    cmds: ["aws cloudfront create-invalidation --paths '/*'"],
    metrics: [{label:"Cache Hit",value:"96%"},{label:"Egress",value:"420 GB/d"},{label:"Edges",value:"310+"}]},
  { id: "waf", name: "AWS WAF", layer: "edge", Icon: FaShieldAlt, color: "#DD344C",
    desc: "Managed rule groups + custom rate-based rules.",
    role: "Blocks OWASP Top 10, bots, and abuse patterns.",
    best: ["Enable AWSManagedRulesCommonRuleSet", "Rate-limit /login endpoints", "Log to Kinesis + Athena"],
    cmds: ["aws wafv2 list-web-acls --scope REGIONAL"],
    metrics: [{label:"Blocked",value:"2.1k/h"},{label:"Rules",value:"18"},{label:"Mode",value:"BLOCK"}]},
  { id: "alb", name: "ALB", layer: "edge", Icon: FaAws, color: "#FF9900",
    desc: "Application Load Balancer — L7 with target groups.",
    role: "TLS termination, path/host routing, WAF hookup.",
    best: ["Enable access logs to S3", "Use HTTP/2 and gRPC target groups", "Sticky sessions per app"],
    cmds: ["aws elbv2 describe-load-balancers"],
    metrics: [{label:"RPS",value:"8.4k"},{label:"5xx",value:"0.02%"},{label:"P95",value:"84ms"}]},

  // Ingress
  { id: "nginx-ing", name: "NGINX Ingress", layer: "ingress", Icon: SiNginx, color: "#009639",
    desc: "Kubernetes ingress controller with rich annotations.",
    role: "TLS, rewrites, rate limits, canary via annotations.",
    best: ["Enable metrics + ServiceMonitor", "Set client_max_body_size", "Use snippet ConfigMaps carefully"],
    cmds: ["kubectl -n ingress-nginx get pods", "kubectl describe ingress web"],
    metrics: [{label:"Conns",value:"14.2k"},{label:"Reqs",value:"6.1k/s"},{label:"P99",value:"128ms"}]},
  { id: "aws-lbc", name: "AWS LB Controller", layer: "ingress", Icon: FaAws, color: "#FF9900",
    desc: "Provisions ALB/NLB from Ingress/Service objects.",
    role: "Native ALB target-group binding for pods (IP mode).",
    best: ["Use IP target type on EKS", "IngressClassParams for shared ALBs", "Enable pod readiness gate"],
    cmds: ["helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller"],
    metrics: [{label:"ALBs",value:"12"},{label:"TGs",value:"48"},{label:"Sync",value:"OK"}]},
  { id: "istio", name: "Istio Gateway", layer: "ingress", Icon: SiIstio, color: "#466BB0",
    desc: "Service mesh with mTLS + traffic shaping.",
    role: "Canary, mirror, retries, circuit breakers at L7.",
    best: ["STRICT mTLS mesh-wide", "PeerAuthentication + AuthorizationPolicy", "Envoy access logs to Loki"],
    cmds: ["istioctl proxy-status", "kubectl apply -f virtualservice.yaml"],
    metrics: [{label:"mTLS",value:"100%"},{label:"VS",value:"36"},{label:"P50",value:"22ms"}]},
  { id: "traefik", name: "Traefik", layer: "ingress", Icon: SiTraefikproxy, color: "#24A1C1",
    desc: "Dynamic edge router with Let's Encrypt built-in.",
    role: "Alternative ingress with middleware chains.",
    best: ["IngressRoute CRD > legacy Ingress", "Middlewares for auth + ratelimit", "Dashboard behind auth"],
    cmds: ["kubectl -n traefik logs deploy/traefik"],
    metrics: [{label:"Routes",value:"41"},{label:"Reqs",value:"3.2k/s"},{label:"Errors",value:"0.01%"}]},

  // Security
  { id: "kyverno", name: "Kyverno", layer: "security", Icon: FaShieldAlt, color: "#1e88e5",
    desc: "Policy-as-code admission controller (YAML native).",
    role: "Validate, mutate, generate resources at admission.",
    best: ["Enforce runAsNonRoot everywhere", "Auto-generate NetworkPolicy per namespace", "Report + Enforce modes"],
    cmds: ["kubectl get cpol", "kyverno test ."],
    metrics: [{label:"Policies",value:"42"},{label:"Blocked",value:"128"},{label:"Score",value:"A+"}]},
  { id: "opa", name: "OPA Gatekeeper", layer: "security", Icon: SiOpenpolicyagent, color: "#7A6BF5",
    desc: "Rego-based policy engine for K8s admission.",
    role: "Constraint templates enforce org-wide guardrails.",
    best: ["Use ConstraintTemplates library", "Audit mode before enforce", "Exempt kube-system carefully"],
    cmds: ["kubectl get constraints"],
    metrics: [{label:"Constraints",value:"31"},{label:"Violations",value:"3"},{label:"Health",value:"OK"}]},
  { id: "falco", name: "Falco", layer: "security", Icon: FaShieldAlt, color: "#00B4A0",
    desc: "Runtime threat detection via eBPF/kernel events.",
    role: "Detects shell-in-container, crypto miners, priv-esc.",
    best: ["Ship alerts to Falcosidekick → Slack", "Custom rules for your workloads", "Enable eBPF driver"],
    cmds: ["falco --list", "kubectl -n falco logs ds/falco"],
    metrics: [{label:"Events",value:"1.4M"},{label:"Alerts",value:"12"},{label:"Rules",value:"210"}]},
  { id: "trivy", name: "Trivy", layer: "security", Icon: FaShieldAlt, color: "#1904DA",
    desc: "Image, IaC, and SBOM vulnerability scanner.",
    role: "Shift-left CVE gating + in-cluster operator scans.",
    best: ["Fail CI on CRITICAL", "Trivy Operator for cluster CVEs", "Cache DB in CI"],
    cmds: ["trivy image myapp:1.0", "trivy k8s cluster"],
    metrics: [{label:"Scans/d",value:"320"},{label:"CVEs",value:"7"},{label:"Fixed",value:"98%"}]},
  { id: "certmgr", name: "cert-manager", layer: "security", Icon: SiLetsencrypt, color: "#003A70",
    desc: "Automated X.509 issuance (Let's Encrypt/ACM PCA).",
    role: "Rotates TLS + mTLS certs across the cluster.",
    best: ["Wildcard via DNS01 (Route53)", "Renew 30 days early", "Monitor cert expiries with Prom"],
    cmds: ["kubectl get certificate -A", "cmctl status certificate web"],
    metrics: [{label:"Certs",value:"64"},{label:"Renewed",value:"14/w"},{label:"Expired",value:"0"}]},
  { id: "secrets", name: "Secrets Manager", layer: "security", Icon: FaKey, color: "#DD344C",
    desc: "AWS Secrets Manager + External Secrets Operator.",
    role: "Sync managed secrets into K8s as sealed refs.",
    best: ["Rotate via Lambda", "IRSA-scoped read only", "Never mount as plain env"],
    cmds: ["aws secretsmanager get-secret-value --secret-id db"],
    metrics: [{label:"Secrets",value:"92"},{label:"Rotated",value:"7d avg"},{label:"Sync",value:"OK"}]},
  { id: "irsa", name: "IRSA", layer: "security", Icon: FaKey, color: "#FF9900",
    desc: "IAM Roles for Service Accounts — pod-level AWS auth.",
    role: "Eliminates node-wide IAM; least-privilege per pod.",
    best: ["One role per ServiceAccount", "Trust policy scoped by SA + NS", "Audit via CloudTrail"],
    cmds: ["eksctl create iamserviceaccount --name app --namespace prod"],
    metrics: [{label:"SAs",value:"58"},{label:"Roles",value:"58"},{label:"Drift",value:"0"}]},

  // Workloads
  { id: "frontend", name: "Frontend", layer: "workloads", Icon: SiKubernetes, color: "#326CE5",
    desc: "Next.js SSR — 6 replicas, HPA 4-20.",
    role: "User-facing web tier behind Istio VirtualService.",
    best: ["Readiness before Ready traffic", "PodDisruptionBudget minAvailable=50%", "Topology spread across AZs"],
    cmds: ["kubectl -n web get deploy frontend", "kubectl rollout status deploy/frontend"],
    metrics: [{label:"Replicas",value:"6/6"},{label:"CPU",value:"340m"},{label:"Restarts",value:"0"}]},
  { id: "backend", name: "Backend API", layer: "workloads", Icon: SiKubernetes, color: "#326CE5",
    desc: "Go REST + gRPC, 12 replicas.",
    role: "Core business logic, talks to Postgres + Redis.",
    best: ["Structured JSON logs", "OTEL traces to Tempo", "Circuit-breaker in Istio"],
    cmds: ["kubectl -n api logs deploy/backend -f", "kubectl top pod -n api"],
    metrics: [{label:"Replicas",value:"12/12"},{label:"P95",value:"48ms"},{label:"Err",value:"0.03%"}]},
  { id: "auth", name: "Auth Service", layer: "workloads", Icon: SiKubernetes, color: "#326CE5",
    desc: "OIDC provider — sessions in Redis.",
    role: "JWT issuance, refresh, session revocation.",
    best: ["Short-lived JWT + refresh rotation", "Rate-limit /login at WAF+ingress", "MFA enforcement"],
    cmds: ["kubectl -n auth exec deploy/auth -- ./healthz"],
    metrics: [{label:"Replicas",value:"4/4"},{label:"Logins/s",value:"120"},{label:"5xx",value:"0"}]},
  { id: "orders", name: "Orders", layer: "workloads", Icon: SiKubernetes, color: "#326CE5",
    desc: "Order lifecycle service, event-driven.",
    role: "Publishes to SNS → SQS fanout.",
    best: ["Idempotency keys", "Outbox pattern", "Retries with backoff+jitter"],
    cmds: ["kubectl -n commerce get pods -l app=orders"],
    metrics: [{label:"Replicas",value:"8/8"},{label:"Msgs/s",value:"640"},{label:"Lag",value:"0"}]},
  { id: "payments", name: "Payments", layer: "workloads", Icon: SiKubernetes, color: "#326CE5",
    desc: "PCI-scoped, isolated namespace + strict NetPol.",
    role: "Stripe/Paddle webhooks + reconciliation.",
    best: ["default-deny NetworkPolicy", "Dedicated node pool", "Sealed secrets only"],
    cmds: ["kubectl -n payments get netpol"],
    metrics: [{label:"Replicas",value:"6/6"},{label:"Success",value:"99.98%"},{label:"P99",value:"210ms"}]},
  { id: "notify", name: "Notifications", layer: "workloads", Icon: FaBell, color: "#326CE5",
    desc: "Email/SMS/push worker — SES + SNS.",
    role: "Consumes SQS, retries with DLQ.",
    best: ["DLQ + alerting", "Template versioning", "Bounce/complaint handling"],
    cmds: ["kubectl -n notify logs deploy/mailer"],
    metrics: [{label:"Sent/d",value:"120k"},{label:"Bounce",value:"0.4%"},{label:"DLQ",value:"0"}]},
  { id: "workers", name: "Workers", layer: "workloads", Icon: FaServer, color: "#326CE5",
    desc: "Background workers + CronJobs.",
    role: "Batch, ETL, scheduled maintenance.",
    best: ["activeDeadlineSeconds on Jobs", "Backoff limits", "Concurrency: Forbid for singletons"],
    cmds: ["kubectl get cronjobs -A"],
    metrics: [{label:"Jobs/d",value:"1.8k"},{label:"Fail",value:"0.2%"},{label:"Queue",value:"12"}]},

  // Data
  { id: "rds", name: "Amazon RDS", layer: "data", Icon: FaAws, color: "#527FFF",
    desc: "Multi-AZ Postgres with read replicas.",
    role: "Primary OLTP with automated backups + PITR.",
    best: ["Enable Performance Insights", "IAM auth for admins", "PITR 35 days"],
    cmds: ["aws rds describe-db-instances"],
    metrics: [{label:"CPU",value:"38%"},{label:"IOPS",value:"12k"},{label:"Conns",value:"280"}]},
  { id: "pg", name: "PostgreSQL", layer: "data", Icon: SiPostgresql, color: "#336791",
    desc: "In-cluster PG for dev + shared caches.",
    role: "CloudNativePG operator, backups to S3.",
    best: ["pgBouncer for connection pooling", "Autovacuum tuning", "WAL to S3"],
    cmds: ["kubectl cnpg status cluster-pg"],
    metrics: [{label:"Size",value:"48 GB"},{label:"TPS",value:"3.1k"},{label:"Replicas",value:"2"}]},
  { id: "mongo", name: "MongoDB", layer: "data", Icon: SiMongodb, color: "#47A248",
    desc: "Document store for catalogs + sessions.",
    role: "Replica set with sharded collections.",
    best: ["Compound indexes for hot queries", "TTL indexes for sessions", "Change streams for CDC"],
    cmds: ["mongosh --eval 'rs.status()'"],
    metrics: [{label:"Ops/s",value:"5.4k"},{label:"Docs",value:"18M"},{label:"Repl",value:"OK"}]},
  { id: "redis", name: "Redis", layer: "data", Icon: SiRedis, color: "#DC382D",
    desc: "Cache + rate-limit + pub/sub.",
    role: "Sub-ms lookups, session storage.",
    best: ["maxmemory-policy allkeys-lru", "AOF for durability", "Separate cluster for pub/sub"],
    cmds: ["redis-cli --stat", "kubectl -n cache logs sts/redis"],
    metrics: [{label:"Hit",value:"98.4%"},{label:"Mem",value:"6.2 GB"},{label:"Ops/s",value:"42k"}]},
  { id: "ebs", name: "EBS + CSI", layer: "data", Icon: FaAws, color: "#527FFF",
    desc: "gp3 block storage via aws-ebs-csi-driver.",
    role: "Persistent volumes for stateful sets.",
    best: ["gp3 > gp2 (baseline IOPS)", "VolumeSnapshot for backups", "Encrypt at rest by default"],
    cmds: ["kubectl get pvc -A", "kubectl get sc"],
    metrics: [{label:"PVs",value:"84"},{label:"Used",value:"1.2 TB"},{label:"Snap/d",value:"84"}]},
  { id: "efs", name: "EFS", layer: "data", Icon: FaAws, color: "#527FFF",
    desc: "Shared NFS for multi-writer workloads.",
    role: "Cross-AZ shared storage for legacy apps.",
    best: ["Use access points per app", "Bursting vs provisioned throughput", "IAM-scoped mounts"],
    cmds: ["aws efs describe-file-systems"],
    metrics: [{label:"FS",value:"4"},{label:"Used",value:"320 GB"},{label:"Clients",value:"36"}]},

  // Cloud
  { id: "s3", name: "S3", layer: "cloud", Icon: FaAws, color: "#569A31",
    desc: "Object storage — assets, backups, data lake.",
    role: "Versioning + lifecycle + Object Lock.",
    best: ["Block Public Access org-wide", "Server-side encryption (SSE-KMS)", "Lifecycle to Glacier"],
    cmds: ["aws s3 ls", "aws s3api get-bucket-policy --bucket app"],
    metrics: [{label:"Buckets",value:"38"},{label:"Objects",value:"140M"},{label:"Size",value:"84 TB"}]},
  { id: "sns", name: "SNS", layer: "cloud", Icon: FaAws, color: "#DD344C",
    desc: "Pub/sub fanout to SQS/Lambda/HTTP.",
    role: "Event backbone for cross-service messaging.",
    best: ["Message filtering to reduce fanout cost", "DLQ per subscription", "KMS-encrypted topics"],
    cmds: ["aws sns list-topics"],
    metrics: [{label:"Msgs/d",value:"2.4M"},{label:"Topics",value:"22"},{label:"Fail",value:"0.01%"}]},
  { id: "sqs", name: "SQS", layer: "cloud", Icon: FaAws, color: "#DD344C",
    desc: "Managed queues (standard + FIFO).",
    role: "Decouples producers from workers.",
    best: ["Long-polling to save cost", "Visibility timeout > worker P99", "DLQ + alarms on age"],
    cmds: ["aws sqs get-queue-attributes --queue-url $Q --attribute-names All"],
    metrics: [{label:"Msgs",value:"18k"},{label:"Age P99",value:"3s"},{label:"DLQ",value:"0"}]},
  { id: "lambda", name: "Lambda", layer: "cloud", Icon: FaAws, color: "#FF9900",
    desc: "Serverless glue + event processors.",
    role: "S3 events, CloudWatch → Slack, cron.",
    best: ["Provisioned concurrency for hot paths", "ARM Graviton for cost", "Powertools for logs/traces"],
    cmds: ["aws lambda list-functions"],
    metrics: [{label:"Fns",value:"48"},{label:"Invocs",value:"9.1M/d"},{label:"Err",value:"0.03%"}]},
  { id: "cw", name: "CloudWatch", layer: "cloud", Icon: FaAws, color: "#FF4F8B",
    desc: "AWS logs, metrics, alarms.",
    role: "Native AWS ingest + composite alarms.",
    best: ["Log retention policies (cost!)", "Metric filters → Prom via YACE", "Composite alarms for noise"],
    cmds: ["aws logs tail /aws/eks/prod --follow"],
    metrics: [{label:"Alarms",value:"128"},{label:"OK",value:"126"},{label:"Firing",value:"2"}]},
  { id: "kms", name: "KMS", layer: "cloud", Icon: FaAws, color: "#DD344C",
    desc: "Customer-managed encryption keys.",
    role: "Envelope encryption for RDS/S3/EBS/Secrets.",
    best: ["One CMK per data domain", "Key rotation enabled", "Deny * on trust policies"],
    cmds: ["aws kms list-keys"],
    metrics: [{label:"CMKs",value:"18"},{label:"Rot.",value:"365d"},{label:"Ops/d",value:"1.4M"}]},

  // Platform
  { id: "eks", name: "Amazon EKS", layer: "platform", Icon: FaAws, color: "#FF9900",
    desc: "Managed control plane, v1.30.",
    role: "3 clusters: dev/stg/prod, multi-AZ.",
    best: ["EKS add-ons managed", "Private endpoint + public via bastion", "Access entries (RBAC)"],
    cmds: ["eksctl get cluster", "aws eks update-kubeconfig --name prod"],
    metrics: [{label:"Nodes",value:"48"},{label:"Pods",value:"612"},{label:"Ver",value:"1.30"}]},
  { id: "helm", name: "Helm", layer: "platform", Icon: SiHelm, color: "#0F1689",
    desc: "Chart packaging + releases.",
    role: "Templated K8s manifests + rollbacks.",
    best: ["Chart lint + kubeval in CI", "Values per env", "helm diff before upgrade"],
    cmds: ["helm upgrade --install app ./chart -f values-prod.yaml"],
    metrics: [{label:"Charts",value:"42"},{label:"Releases",value:"128"},{label:"Ver",value:"3.15"}]},
  { id: "argocd", name: "Argo CD", layer: "platform", Icon: SiArgo, color: "#EF7B4D",
    desc: "GitOps continuous delivery.",
    role: "Reconciles cluster to Git state.",
    best: ["App-of-apps pattern", "AutoSync + selfHeal", "SSO via OIDC"],
    cmds: ["argocd app sync web", "argocd app list"],
    metrics: [{label:"Apps",value:"84"},{label:"Sync",value:"OK"},{label:"OoS",value:"2"}]},
  { id: "tf", name: "Terraform", layer: "platform", Icon: SiTerraform, color: "#7B42BC",
    desc: "IaC for AWS + K8s + observability stack.",
    role: "Modules per domain, remote state in S3+DDB.",
    best: ["tflint + tfsec in CI", "Atlantis for PR workflow", "State lock via DynamoDB"],
    cmds: ["terraform plan -out plan.tfplan", "terraform apply plan.tfplan"],
    metrics: [{label:"Modules",value:"36"},{label:"Envs",value:"3"},{label:"Ver",value:"1.9"}]},
  { id: "gha", name: "GitHub Actions", layer: "platform", Icon: SiGithubactions, color: "#2088FF",
    desc: "CI: build, scan, sign, publish.",
    role: "OIDC to AWS — no long-lived keys.",
    best: ["Reusable workflows", "Concurrency groups", "OIDC + STS for AWS auth"],
    cmds: ["gh workflow run deploy.yml"],
    metrics: [{label:"Runs/d",value:"420"},{label:"P50",value:"3m 20s"},{label:"Success",value:"98.7%"}]},
  { id: "prom", name: "Prometheus", layer: "platform", Icon: SiPrometheus, color: "#E6522C",
    desc: "Metrics via kube-prometheus-stack.",
    role: "Scrape, alert, recording rules.",
    best: ["Long-term storage in Thanos/Mimir", "Recording rules for expensive queries", "Alertmanager routing"],
    cmds: ["kubectl -n monitoring port-forward svc/prometheus 9090"],
    metrics: [{label:"Series",value:"4.2M"},{label:"Targets",value:"312"},{label:"Rules",value:"148"}]},
  { id: "grafana", name: "Grafana", layer: "platform", Icon: SiGrafana, color: "#F46800",
    desc: "Dashboards for metrics/logs/traces.",
    role: "Single pane over Prom + Loki + Tempo.",
    best: ["Dashboards as code (JSON in Git)", "Folder-based RBAC", "Alert on SLO burn rate"],
    cmds: ["grafana-cli plugins ls"],
    metrics: [{label:"Dashboards",value:"64"},{label:"Users",value:"38"},{label:"Alerts",value:"22"}]},
  { id: "otel", name: "OpenTelemetry", layer: "platform", Icon: SiOpentelemetry, color: "#F5A800",
    desc: "Vendor-neutral traces/metrics/logs.",
    role: "Collector deploys as DaemonSet + Gateway.",
    best: ["Tail-based sampling at gateway", "Resource attributes for env/service", "Batch + memory_limiter"],
    cmds: ["kubectl -n obs logs ds/otel-collector"],
    metrics: [{label:"Spans/s",value:"12k"},{label:"Drop",value:"0%"},{label:"Sampled",value:"5%"}]},
];

// GitOps pipeline stages
export const GITOPS_STAGES = [
  { id: "dev",       name: "Developer",     Icon: SiGit,          color: "#F05033" },
  { id: "gh",        name: "GitHub",        Icon: SiGithub,       color: "#f0f6fc" },
  { id: "gha",       name: "Actions",       Icon: SiGithubactions, color: "#2088FF" },
  { id: "test",      name: "Unit Tests",    Icon: FaShieldAlt,    color: "#22c55e" },
  { id: "sonar",     name: "SonarQube",     Icon: SiSonarqube,    color: "#4E9BCD" },
  { id: "semgrep",   name: "Semgrep",       Icon: FaShieldAlt,    color: "#1B69B6" },
  { id: "trivy",     name: "Trivy",         Icon: FaShieldAlt,    color: "#1904DA" },
  { id: "docker",    name: "Docker Build",  Icon: SiDocker,       color: "#2496ED" },
  { id: "cosign",    name: "Cosign",        Icon: FaLock,         color: "#a855f7" },
  { id: "ecr",       name: "ECR",           Icon: FaAws,          color: "#FF9900" },
  { id: "helm",      name: "Update Helm",   Icon: SiHelm,         color: "#0F1689" },
  { id: "gitops",    name: "GitOps Repo",   Icon: SiGit,          color: "#F05033" },
  { id: "argo",      name: "Argo CD",       Icon: SiArgo,         color: "#EF7B4D" },
  { id: "eks",       name: "EKS Rollout",   Icon: SiKubernetes,   color: "#326CE5" },
  { id: "probe",     name: "Readiness",     Icon: FaChartLine,    color: "#22c55e" },
  { id: "shift",     name: "Traffic Shift", Icon: SiIstio,        color: "#466BB0" },
  { id: "prod",      name: "Production",    Icon: SiKubernetes,   color: "#22c55e" },
];

export const INCIDENTS = [
  { id: "podcrash",   label: "Pod Crash",        node: "backend" },
  { id: "oom",        label: "OOMKilled",        node: "orders"  },
  { id: "clbo",       label: "CrashLoopBackOff", node: "auth"    },
  { id: "imgpull",    label: "ImagePullBackOff", node: "frontend"},
  { id: "nodefail",   label: "Node Failure",     node: "eks"     },
  { id: "cpu",        label: "High CPU",         node: "backend" },
  { id: "mem",        label: "High Memory",      node: "redis"   },
  { id: "disk",       label: "Disk Pressure",    node: "ebs"     },
  { id: "netfail",    label: "Network Failure",  node: "istio"   },
  { id: "dbfail",     label: "Database Failure", node: "rds"     },
];
